/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))'
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))'
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))'
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))'
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))'
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))'
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))'
        },
        border: 'hsl(var(--border))',
        input:  'hsl(var(--input))',
        ring:   'hsl(var(--ring))',

        // ── Semantic status tokens ──────────────────────────────
        // Use success/warning/danger everywhere instead of
        // green-*/amber-*/red-* hardcoded Tailwind color names.
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))'
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--warning-foreground))'
        },
        danger: {
          DEFAULT: 'hsl(var(--danger))',
          foreground: 'hsl(var(--danger-foreground))'
        },
        'light-active': {
          DEFAULT: 'hsl(var(--light-active))',
          foreground: 'hsl(var(--light-active-foreground))'
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        field: '1.2rem',
        section: '1.5rem',
        control: 'var(--radius-control)',
        card: 'var(--radius-card)',
        panel: 'var(--radius-panel)',
        modal: 'var(--radius-modal)',
        dashboard: '2.5rem',
        hero: '3rem',
        scene: '3.5rem',
        showcase: '4rem',
        pill: 'var(--radius-pill)'
      },
      spacing: {
        'sidebar-expanded': '15.5rem',
        'sidebar-collapsed': '4.75rem',
        'brand-indent': '2.875rem',
        'glow-orb': '31.25rem',
        'touch-target': '3rem',
        'audio-picker-sm': '7.5rem',
        'audio-picker-md': '9rem',
        'audio-picker-lg': '10.5rem',
        'popover-sm': '20rem',
        'popover-responsive': 'min(20rem, calc(100vw - 2rem))',
        'toast-responsive': 'min(540px, calc(100vw - 2rem))',
        'modal-wide': '60rem',
        'modal-xl': '70rem',
        'content-standard': '80rem',
        'content-wide': '100rem',
        'clock-shell-compact': 'clamp(0.85rem, 2.4cqi, 1.35rem)',
        'clock-shell': 'clamp(1rem, 3cqi, 1.65rem)',
        'clock-shell-roomy': 'clamp(1rem, 3.2cqi, 1.8rem)',
        'clock-gap-compact': 'clamp(0.55rem, 1.7cqi, 0.85rem)',
        'clock-gap': 'clamp(0.65rem, 1.9cqi, 1rem)',
        'clock-gap-layout': 'clamp(0.85rem, 3cqi, 1.45rem)',
        'clock-gap-layout-lg': 'clamp(0.9rem, 3cqi, 1.75rem)',
        'clock-dial': 'clamp(8.6rem, 32cqi, 14rem)',
        'clock-dial-premium': 'clamp(10rem, 38cqi, 17rem)',
        'clock-dial-classic': 'clamp(7.5rem, 23cqi, 11.25rem)',
        'clock-dial-minimal': 'clamp(7.2rem, 24cqi, 12rem)',
        'clock-orb': 'clamp(3rem, 7.5cqi, 4rem)',
        'clock-pad-x': 'clamp(1.15rem, 4.2cqi, 2.45rem)',
        'clock-pad-y': 'clamp(0.8rem, 2.1cqi, 1.2rem)',
        'clock-section-y': 'clamp(0.8rem, 2.5cqi, 1.5rem)',
        'clock-section-y-compact': 'clamp(0.6rem, 2cqi, 1.2rem)',
        'widget-pad-x': 'clamp(1rem, 3cqi, 2rem)',
        'widget-pad-y': 'clamp(0.65rem, 1.5cqi, 1.1rem)',
        'widget-spacer': 'clamp(0.2rem, 0.6cqi, 0.5rem)',
        'room-icon': '1.125rem',
        'control-icon': '1.1rem',
        'demo-button': '9rem',
        'form-md': '26rem',
        'search-panel': '22rem',
      },
      width: {
        'hairline': '1px',
        'rule': '2px',
        'percent-64': '64%',
        'percent-88': '88%',
        'conversation-mobile': '92%',
        'camera-viewer': '112rem',
        'atmosphere': '100vmax',
        'native-camera-toast': 'min(420px, calc(100vw - 2rem))',
        'device-icon-sm': 'clamp(1.25rem, 12cqi, 1.75rem)',
        'device-icon-lg': 'clamp(3rem, 38cqi, 7rem)',
        'section-card-sm': '8.25rem',
        'section-card-md': '9.25rem',
        'section-card-lg': '10rem',
      },
      height: {
        'screen-dvh': '100dvh',
        'assistant-loading': '60vh',
        'hairline': '1px',
        'rule': '2px',
        'camera-viewer': 'calc(100dvh - 1rem)',
        'camera-viewer-sm': 'calc(100dvh - 2rem)',
        'atmosphere': '100vmax',
        'topology-empty': '21.875rem',
        'room-icon': '1.125rem',
        'control-icon': '1.1rem',
        'device-icon-sm': 'clamp(1.25rem, 12cqi, 1.75rem)',
        'device-icon-lg': 'clamp(3rem, 38cqi, 7rem)',
      },
      minHeight: {
        'onboarding': 'calc(100vh - theme(spacing.16))',
        'screen-half': '50vh',
        'empty-sm': '25rem',
        'empty-md': '31.25rem',
        'empty-lg': '32.5rem',
        'suggested-command': '3.25rem',
        'conversation-sm': '42vh',
        'conversation-md': '48vh',
        'conversation-lg': '52vh',
        'device-tile-sm': '7.75rem',
        'device-tile': '8rem',
        'device-tile-md': '8.25rem',
        'device-tile-lg': '9rem',
        'scene-card-sm': '5.75rem',
        'scene-card': '6.5rem',
        'section-card-sm': '8.25rem',
        'section-card-md': '9.25rem',
        'section-card-lg': '10rem',
        'native-camera-card': '8.5rem',
        'camera-card': '12rem',
        'clock-card': '14rem',
        'curtain-card': '12rem',
        'curtain-card-lg': '13rem',
      },
      maxHeight: {
        'modal-safe': 'calc(100vh - 2rem)',
        'modal-safe-lg': 'calc(100vh - 3rem)',
        'sheet': '82vh',
        'viewport-modal': '92dvh',
        'viewport-panel': '92vh',
        'viewport-panel-sm': '90vh',
        'picker': '15rem',
        'camera-list': '22.5rem',
        'topology-list': '21.25rem',
        'timeline': '37.5rem',
        'section-editor': '58vh',
        'section-modal': '88vh',
      },
      maxWidth: {
        'content-standard': '80rem',
        'content-wide': '100rem',
        'camera-viewer': '112rem',
        'toast': '26.25rem',
        'composer-bubble': '85%',
        'conversation-user': '64%',
        'conversation-assistant': '74%',
        'native-camera-modal': 'min(1120px, calc(100vw - 2rem))',
        'native-camera-form': 'min(960px, calc(100vw - 2rem))',
        'native-camera-toast': 'min(420px, calc(100vw - 2rem))',
        'copy-2xs': '6.25rem',
        'copy-xs': '7.5rem',
        'copy-sm': '8.75rem',
        'copy-md': '9.375rem',
        'copy-lg': '12.5rem',
        'copy-2xl': '15.625rem',
        'copy-xl': '13rem',
        'form-md': '26rem',
      },
      minWidth: {
        'data-table': '47.5rem',
        'demo-button': '9rem',
        'execution-time': '6.875rem',
        'inbox-device': '8.75rem',
      },
      fontSize: {
        // Product typography scale. Content that a resident needs to read is
        // never smaller than 12px. `nano` is intentionally decorative only.
        nano: ['0.625rem', { lineHeight: '0.875rem' }],
        micro: ['0.75rem', { lineHeight: '1rem' }],
        label: ['0.75rem', { lineHeight: '1rem' }],
        caption: ['0.8125rem', { lineHeight: '1.125rem' }],
        'body-compact': ['0.875rem', { lineHeight: '1.25rem' }],
        body: ['0.9375rem', { lineHeight: '1.5rem' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem' }],
        'card-title': ['1rem', { lineHeight: '1.25rem' }],
        'section-title': ['1.125rem', { lineHeight: '1.5rem' }],
        'panel-title': ['1.25rem', { lineHeight: '1.625rem' }],
        'view-title': ['1.5rem', { lineHeight: '1.875rem' }],
        'display-title': ['1.75rem', { lineHeight: '2.125rem' }],
        'hero-title': ['2.125rem', { lineHeight: '2.375rem' }],
        'hero-title-lg': ['2.75rem', { lineHeight: '1' }],
        'widget-title-fluid': ['clamp(1.15rem,3.1cqi,2rem)', { lineHeight: '1.05' }],
        'widget-title-compact-fluid': ['clamp(1rem,2.4cqi,1.55rem)', { lineHeight: '1.08' }],
        'widget-title-small-fluid': ['clamp(0.9rem,2cqi,1.25rem)', { lineHeight: '1.12' }],
        'dashboard-section-title-fluid': ['clamp(1.125rem,2.2cqi,1.5rem)', { lineHeight: '1.2' }],
        'widget-caption-fluid': ['clamp(0.72rem,1.45cqi,0.98rem)', { lineHeight: '1.2' }],
        // Device-card copy stays within the shared body scale at every width.
        'widget-body-fluid': ['clamp(0.75rem,2.2cqi,0.875rem)', { lineHeight: '1.25' }],
        'widget-body-lg-fluid': ['clamp(0.8125rem,2.4cqi,0.9375rem)', { lineHeight: '1.25' }],
        'widget-metric-fluid': ['clamp(1.75rem,18cqi,2.25rem)', { lineHeight: '1' }],
        'clock-caption-fluid': ['clamp(0.55rem,1.3cqi,0.82rem)', { lineHeight: '1.15' }],
        'clock-label-fluid': ['clamp(0.49rem,1.2cqi,0.72rem)', { lineHeight: '1.1' }],
        'clock-micro-fluid': ['clamp(0.48rem,1.18cqi,0.66rem)', { lineHeight: '1.1' }],
        'clock-seconds-fluid': ['clamp(0.54rem,1.6cqi,0.86rem)', { lineHeight: '1.1' }],
        'clock-period-fluid': ['clamp(0.44rem,1.2cqi,0.66rem)', { lineHeight: '1.1' }],
        'clock-time-2xl-fluid': ['clamp(4rem,17cqi,8.4rem)', { lineHeight: '0.92' }],
        'clock-time-xl-fluid': ['clamp(3.35rem,13.5cqi,6.7rem)', { lineHeight: '0.94' }],
        'clock-time-lg-fluid': ['clamp(2.75rem,10.5cqi,5.5rem)', { lineHeight: '0.96' }],
        'clock-time-md-fluid': ['clamp(2.35rem,8cqi,4.5rem)', { lineHeight: '0.98' }],
        'clock-analog-label-fluid': ['clamp(0.58rem,1.3cqi,0.78rem)', { lineHeight: '1.1' }],
        'clock-analog-time-fluid': ['clamp(2.5rem,8.2cqi,4.45rem)', { lineHeight: '0.95' }],
        'clock-minimal-label-fluid': ['clamp(0.48rem,1.1cqi,0.65rem)', { lineHeight: '1.1' }],
        'clock-minimal-time-fluid': ['clamp(2.35rem,8.5cqi,4.7rem)', { lineHeight: '0.95' }],
        'clock-digital-label-fluid': ['clamp(0.53rem,1.25cqi,0.72rem)', { lineHeight: '1.1' }],
        'clock-digital-body-fluid': ['clamp(0.52rem,1.35cqi,0.78rem)', { lineHeight: '1.15' }],
        'clock-digital-micro-fluid': ['clamp(0.38rem,0.95cqi,0.5rem)', { lineHeight: '1' }]
      },
      letterSpacing: {
        micro: '0.04em',
        control: '0.06em',
        status: '0.08em',
        label: '0.1em',
        'label-wide': '0.12em',
        'label-wider': '0.14em',
        'label-ultra': '0.16em',
        'label-hero': '0.18em',
        clock: '0.42em',
        'display-tight': '-0.035em',
        'clock-tight': '-0.08em',
        'clock-time': '-0.085em',
      },
      lineHeight: {
        'display-tight': '0.95',
      },
      blur: {
        'micro': '1px',
        'surface': '2px',
        'energy': '60px',
        glow: '80px',
        'glow-xl': '120px',
      },
      boxShadow: {
        'sidebar-open': '4px 0 32px -4px hsl(210 30% 2% / 0.6)',
        'modal-premium': '0 28px 90px hsl(var(--foreground) / 0.18)',
        'primary-focus': '0 0 0 4px hsl(var(--primary) / 0.10)',
        'primary-soft': '0 10px 24px hsl(var(--primary) / 0.24)',
        'primary-button': '0 18px 38px hsl(var(--primary) / 0.24)',
        'primary-button-hover': '0 22px 46px hsl(var(--primary) / 0.28)',
        'primary-ring': '0 0 50px hsl(var(--primary) / 0.3)',
        'primary-glow': '0 0 14px hsl(var(--primary) / 0.75)',
        'primary-room-icon': '0 0 24px hsl(var(--primary) / 0.16)',
        'primary-beacon': '0 0 8px hsl(var(--primary) / 0.5)',
        'primary-halo': '0 0 40px hsl(var(--primary) / 0.25)',
        'primary-pill': '0 0 10px hsl(var(--primary) / 0.3)',
        'primary-warm': '0 16px 42px hsl(var(--primary) / 0.18)',
        'primary-room': '0 18px 46px hsl(var(--primary) / 0.10)',
        'surface-soft': '0 16px 44px hsl(var(--foreground) / 0.07)',
        'surface-card': '0 12px 34px hsl(var(--foreground) / 0.07)',
        'surface-room': '0 18px 46px hsl(var(--foreground) / 0.12)',
        'scene-modal': '0 50px 100px -20px rgba(0, 0, 0, 0.5)',
        'clock-digital': '0 22px 60px hsl(var(--background) / 0.28)',
        'curtain-track': '0 -4px 12px hsl(var(--foreground) / 0.18)',
        'success-beacon': '0 0 8px rgba(34, 197, 94, 0.5)',
        'success-pill': '0 0 10px rgba(34, 197, 94, 0.1)',
        'warning-soft': '0 0 18px hsl(var(--warning) / 0.18)',
        'light-warm-sm': '0 0 8px rgba(251, 191, 36, 0.5)',
        'light-warm-lg': '0 0 16px rgba(251, 191, 36, 0.6)',
        'danger-dot': '0 0 8px hsl(var(--destructive))',
      },
      backgroundImage: {
        'dashboard-grid': 'radial-gradient(circle at 1px 1px, hsl(var(--foreground) / 0.05) 1px, transparent 0)',
        'automation-action': 'linear-gradient(145deg, hsl(var(--card)), hsl(var(--primary) / 0.07))',
        'assistant-ready': 'radial-gradient(circle at 16% 8%, hsl(var(--primary) / 0.12), transparent 28%), linear-gradient(145deg, hsl(var(--card) / 0.96), hsl(var(--background) / 0.92))',
        'clock-neutral': 'radial-gradient(circle at 50% 32%, hsl(var(--foreground) / 0.045), transparent 36%), linear-gradient(145deg, hsl(var(--card) / 0.92), hsl(var(--background) / 0.98))',
        'clock-analog': 'radial-gradient(circle at 30% 44%, hsl(var(--primary) / 0.18), transparent 38%), radial-gradient(circle at 78% 64%, hsl(var(--foreground) / 0.04), transparent 34%), linear-gradient(145deg, hsl(var(--card) / 0.90), hsl(var(--background) / 0.98))',
        'clock-minimal': 'radial-gradient(circle at 50% 44%, hsl(var(--foreground) / 0.04), transparent 40%), linear-gradient(145deg, hsl(var(--card) / 0.90), hsl(var(--background) / 0.98))',
        'clock-warm': 'radial-gradient(circle at 25% 26%, hsl(var(--primary) / 0.18), transparent 36%), radial-gradient(circle at 76% 74%, hsl(var(--foreground) / 0.035), transparent 32%), linear-gradient(145deg, hsl(var(--card) / 0.92), hsl(var(--background) / 0.98))',
        'clock-sheen': 'linear-gradient(120deg, transparent 0%, hsl(var(--foreground) / 0.035) 48%, transparent 100%)',
        'dormant-radial': 'radial-gradient(circle at center, hsl(var(--primary) / 0.05), transparent 70%)',
        'energy-radial': 'radial-gradient(ellipse at center, hsl(var(--warning) / 0.03) 0%, transparent 70%)',
        'scene-preview': 'radial-gradient(circle at 90% 20%, hsl(var(--primary) / 0.25), transparent 16%), linear-gradient(135deg, hsl(var(--primary) / 0.24), hsl(var(--card) / 0.95) 42%, hsl(var(--background) / 0.98))',
        'room-card': 'radial-gradient(circle at 18% 12%, hsl(var(--primary) / 0.08), transparent 30%), linear-gradient(145deg, hsl(var(--card) / 0.99), hsl(var(--background) / 0.96))',
        'room-card-dark': 'radial-gradient(circle at 90% 10%, hsl(var(--primary) / 0.18), transparent 34%), linear-gradient(145deg, hsl(var(--card) / 0.96), hsl(var(--background) / 0.98))',
        'room-card-aura': 'radial-gradient(circle at 14% 18%, hsl(var(--primary) / 0.08), transparent 28%)',
        'room-card-rich': 'radial-gradient(circle at 82% 18%, hsl(var(--primary) / 0.2), transparent 32%), linear-gradient(145deg, hsl(var(--card)), hsl(var(--primary) / 0.09))',
        'room-card-quiet': 'radial-gradient(circle at 85% 20%, hsl(var(--primary) / 0.18), transparent 30%), hsl(var(--card))',
        'device-active': 'linear-gradient(145deg, hsl(var(--card)), hsl(var(--primary) / 0.12))',
        'device-active-dark': 'radial-gradient(circle at 50% 20%, hsl(var(--primary) / 0.24), transparent 38%), hsl(var(--card))',
      },
      backgroundSize: {
        dashboard: '20px 20px',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)'
      }
    }
  },
  plugins: [require("tailwindcss-animate")],
}
