import { useCallback, useEffect, useRef, useState } from 'react';
import { Blinds, CheckCircle2, Cloud, Link2, RefreshCw, ShieldCheck, Unlink } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { useTranslation } from 'react-i18next';
import { API_BASE_URL } from '../config';
import { apiFetch } from '../lib/apiClient';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Input } from '../components/ui/Input';
import { SearchableSelectField } from '../components/ui/SearchableSelectField';

interface TuyaStatus { available: boolean; configured: boolean; userCodeHint: string; updatedAt: string | null; }
interface TuyaSession { qrToken: string; qrCode: string; expiresAt: number | null; }
interface Home { id: string; name: string; }
interface Cover { id: string; name: string; category: string; online: boolean; }

export const TuyaSettingsView = () => {
  const { t } = useTranslation();
  const [status, setStatus] = useState<TuyaStatus | null>(null); const [homes, setHomes] = useState<Home[]>([]); const [covers, setCovers] = useState<Cover[]>([]);
  const [userCode, setUserCode] = useState(''); const [session, setSession] = useState<TuyaSession | null>(null); const [homeId, setHomeId] = useState('');
  const [busy, setBusy] = useState<'link' | 'covers' | string | null>(null); const [notice, setNotice] = useState<{ type: 'success' | 'error'; text: string } | null>(null); const polling = useRef<number | null>(null);
  const stopPolling = useCallback(() => { if (polling.current !== null) { window.clearInterval(polling.current); polling.current = null; } }, []);
  const load = useCallback(async () => { try { const [statusResponse, homesResponse] = await Promise.all([apiFetch(`${API_BASE_URL}/api/v1/integrations/tuya/status`), apiFetch(`${API_BASE_URL}/api/v1/homes`)]); if (!statusResponse.ok || !homesResponse.ok) throw new Error('load'); const nextStatus = await statusResponse.json() as TuyaStatus; const nextHomes = await homesResponse.json() as Home[]; setStatus(nextStatus); setHomes(nextHomes); setHomeId((current) => current || nextHomes[0]?.id || ''); } catch { setNotice({ type: 'error', text: t('tuya.messages.load_error') }); } }, [t]);
  useEffect(() => { void load(); return stopPolling; }, [load, stopPolling]);
  const complete = useCallback(async (nextSession: TuyaSession, code: string) => { const response = await apiFetch(`${API_BASE_URL}/api/v1/integrations/tuya/authorization/complete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userCode: code, qrToken: nextSession.qrToken }) }); if (!response.ok) return false; const payload = await response.json() as { authorized: boolean }; if (!payload.authorized) return false; stopPolling(); setSession(null); setNotice({ type: 'success', text: t('tuya.messages.authorized') }); await load(); return true; }, [load, stopPolling, t]);
  const startAuthorization = async () => { setBusy('link'); setNotice(null); try { const response = await apiFetch(`${API_BASE_URL}/api/v1/integrations/tuya/authorization`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userCode }) }); if (!response.ok) throw new Error('link'); const nextSession = await response.json() as TuyaSession; setSession(nextSession); stopPolling(); polling.current = window.setInterval(() => { void complete(nextSession, userCode); }, 3000); } catch { setNotice({ type: 'error', text: t('tuya.messages.authorization_error') }); } finally { setBusy(null); } };
  const disconnect = async () => { setBusy('disconnect'); try { const response = await apiFetch(`${API_BASE_URL}/api/v1/integrations/tuya/authorization`, { method: 'DELETE' }); if (!response.ok) throw new Error('disconnect'); setCovers([]); setNotice({ type: 'success', text: t('tuya.messages.disconnected') }); await load(); } catch { setNotice({ type: 'error', text: t('tuya.messages.disconnect_error') }); } finally { setBusy(null); } };
  const loadCovers = async () => { setBusy('covers'); try { const response = await apiFetch(`${API_BASE_URL}/api/v1/integrations/tuya/covers`); if (!response.ok) throw new Error('covers'); setCovers(await response.json() as Cover[]); } catch { setNotice({ type: 'error', text: t('tuya.messages.covers_error') }); } finally { setBusy(null); } };
  const importCover = async (cover: Cover) => { if (!homeId) return; setBusy(cover.id); try { const response = await apiFetch(`${API_BASE_URL}/api/v1/integrations/tuya/covers/import`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ homeId, sourceId: cover.id, name: cover.name }) }); if (!response.ok) throw new Error('import'); setNotice({ type: 'success', text: t('tuya.messages.import_success', { name: cover.name }) }); } catch { setNotice({ type: 'error', text: t('tuya.messages.import_error', { name: cover.name }) }); } finally { setBusy(null); } };
  return <div className="mx-auto w-full max-w-5xl space-y-6 pb-10">
    <Card className="p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><div className="rounded-xl bg-primary/10 p-3 text-primary"><Cloud className="h-6 w-6" /></div><div><h1 className="text-title font-semibold">{t('tuya.title')}</h1><p className="text-body text-muted-foreground">{t('tuya.subtitle')}</p></div></div><div className="flex items-center gap-2 text-caption text-muted-foreground"><ShieldCheck className="h-4 w-4 text-success" />{t('tuya.local_only')}</div></div></Card>
    {notice && <div className={notice.type === 'success' ? 'rounded-xl border border-success/30 bg-success/10 p-3 text-body text-success' : 'rounded-xl border border-danger/30 bg-danger/10 p-3 text-body text-danger'}>{notice.text}</div>}
    {!status?.available ? <Card className="p-6 text-body text-muted-foreground">{t('tuya.unavailable')}</Card> : !status.configured ? <Card className="p-6"><div className="grid gap-6 md:grid-cols-[minmax(0,1fr)_13rem]"><div className="space-y-4"><h2 className="text-section font-semibold">{t('tuya.connect_title')}</h2><p className="text-body text-muted-foreground">{t('tuya.connect_description')}</p><Input label={t('tuya.user_code')} value={userCode} onChange={(event) => setUserCode(event.target.value)} placeholder={t('tuya.user_code_placeholder')} required /><Button type="button" onClick={startAuthorization} disabled={busy !== null || !userCode.trim()}><Link2 className={busy === 'link' ? 'mr-2 h-4 w-4 animate-spin' : 'mr-2 h-4 w-4'} />{t('tuya.continue')}</Button></div>{session && <div className="flex flex-col items-center rounded-xl border border-border bg-muted/30 p-4 text-center"><QRCodeSVG value={session.qrCode} size={164} includeMargin /><p className="mt-3 text-caption text-muted-foreground">{t('tuya.scan_qr')}</p></div>}</div></Card> : <Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-section font-semibold">{t('tuya.connected_title')}</h2><p className="text-body text-muted-foreground">{t('tuya.connected_description', { userCode: status.userCodeHint })}</p></div><Button type="button" variant="outline" onClick={disconnect} disabled={busy !== null}><Unlink className="mr-2 h-4 w-4" />{t('tuya.disconnect')}</Button></div></Card>}
    {status?.configured && <Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-section font-semibold">{t('tuya.covers_title')}</h2><p className="text-body text-muted-foreground">{t('tuya.covers_subtitle')}</p></div><div className="flex flex-wrap items-end gap-2"><SearchableSelectField label={t('tuya.target_home')} value={homeId} onChange={setHomeId} options={homes.map((home) => ({ value: home.id, label: home.name }))} placeholder={t('tuya.select_home')} size="small" className="min-w-52" /><Button type="button" onClick={loadCovers} disabled={busy !== null}><RefreshCw className={busy === 'covers' ? 'mr-2 h-4 w-4 animate-spin' : 'mr-2 h-4 w-4'} />{t('tuya.load_covers')}</Button></div></div>{covers.length > 0 && <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{covers.map((cover) => <div key={cover.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><Blinds className="h-5 w-5 text-primary" /><span className={cover.online ? 'text-caption text-success' : 'text-caption text-muted-foreground'}>{cover.online ? t('tuya.online') : t('tuya.offline')}</span></div><p className="mt-3 truncate font-medium">{cover.name}</p><p className="text-caption text-muted-foreground">{cover.category}</p><Button className="mt-4 w-full" size="sm" onClick={() => importCover(cover)} disabled={busy !== null || !homeId}>{busy === cover.id ? <RefreshCw className="h-4 w-4 animate-spin" /> : <><CheckCircle2 className="mr-2 h-4 w-4" />{t('tuya.import')}</>}</Button></div>)}</div>}</Card>}
  </div>;
};